image: clojure:lein-2.8.1

variables:
  BEFREE_DATABASE: "jdbc:postgresql://localhost:5432/befree?user=postgres&password=postgres"

test:
  stage: test
  script:
    - lein test

build:
  stage: build
  artifacts:
    paths:
    - target/
  script:
    - lein uberjar